SEED: 1
wandb_enable: False
wandb_name: diffuse
output_dir: outputs/experiments/${now:%H-%M-%S}/
checkpoint: null
checkpoint_strict_load: False
world_size: 1
cuda_device: 0
project_root: ${oc.env:HOME}/ysz/WORK
TRAIN_DATASET:
  spa_dir: ${oc.env:HOME}/data/package_SPA_cls/train/feature
  task_instr_file: ${project_root}/assets/tasks_instructions.json
  task_instr_embeds_file: ${oc.env:HOME}/data/package_SPA_cls/train/instr_embeds_clip.npy
  instr_embed_type: all
  tasks_file: ${project_root}/assets/tasks_peract.json
  taskvars_filter: [
    "close_jar",
    "insert_onto_square_peg",
    "light_bulb_in",
    "meat_off_grill",
    "open_drawer",
    "place_cups",
    "place_shape_in_shape_sorter",
    "place_wine_at_rack_location",
    "push_buttons",
    "put_groceries_in_cupboard",
    "put_item_in_drawer",
    "put_money_in_safe",
    "reach_and_drag",
    "slide_block_to_color_target",
    "stack_blocks",
    "stack_cups",
    "sweep_to_dustpan_of_size",
    "turn_tap"
  ]
  include_last_step: False
  #可以筛选想要单独测评的任务
TRAIN:
  train_batch_size: 64
  val_batch_size: 100
  gradient_accumulation_steps: 1  
  resume_encoder_only: False
  num_train_steps: null #总步数
  num_epochs: 800
  n_workers: 4
  pin_mem: True

  grad_norm: 200
  log_steps: 500
  bar_steps: 100 #进度条
  save_steps: 2000

  optim: 'adamw'
  learning_rate: 1e-4
  weight_decay: 0.05 #权重衰减
  betas: [0.9, 0.9]

  lr_sched: 'cosine'
  warmup_steps: 4000
  num_cosine_cycles: 0.5
  
  # lr_sched: 'tri_stage'
  # init_lr_scale: 0.1
  # final_lr_scale: 1e-6
  # phase_ratio: "(0.02, 0.08, 0.9)"
  # tri_decay: cosine   # or linear

MODEL:
  model_class: DP
  sigma_data: 0.5
  sigma_min: 0.001
  sigma_max: 80
  repeat_num: 128
  sigma_sample_density_type: 'loglogistic'
  noise_scheduler: 'exponential'
  INNER_MODEL:
    repeat_num: ${MODEL.repeat_num}
    embed_dim: 512
    n_heads: 8
    attn_pdrop: 0.3
    resid_pdrop: 0.1
    n_enc_layers: 4
    n_dec_layers: 6
    block_size: 4
    action_dim: 8
    txt_ft_size: 512
    mlp_pdrop: 0.05
    embed_pdrob: 0
    bias: False
    use_rot_embed: False
    rotary_xpos: False
    use_noise_encoder: False
    linear_output: False
    encoder_use_cross_attention: False
    enable_flash: False
